name: Scrape Active Interventions

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:

    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch and format active interventions json
      run: |-
        curl https://nycrtspublicportal.azurewebsites.net/data/activeinterventioncases | jq '.value' > activeinterventioncases.json

    - name: Create interventions CSV
      run: |-
        jq -r '(.[0] | keys_unsorted) as $keys | ([$keys] + map([.[ $keys[] ]])) [] | @csv' activeinterventioncases.json > csv/activeinterventioncases.csv


    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Active interventions: ${timestamp}" || exit 0
        git push
