name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0/3 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Fetch and format active interventions json
      run: |-
        curl https://nycrtspublicportal.azurewebsites.net/data/activeinterventioncases | jq '.value' > activeinterventioncases.json
    - name: Create interventions CSV
      run: |-
        jq -r '(.[0] | keys_unsorted) as $keys | ([$keys] + map([.[ $keys[] ]])) [] | @csv' activeinterventioncases.json > csv/activeinterventioncases.csv
    - name: Fetch and format summary json
      run: |-
        curl https://nycrtspublicportal.azurewebsites.net/data/summary | jq '.' > summary.json
    - name: Fetch and format summary json
      run: |-
        curl https://testingresults.schools.nyc/surveytesting/summary > testingresults-summary.html
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6.8'        
    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r parse/requirements.txt        
    - name: execute py script
      run: python parse/summary.py
    - name: execute py script
      run: python parse/testingresults.py
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
